"ENV_NAME": "yokai_game"
"ENV_KWARGS": {}
"LR": 5.0e-4
"NUM_ENVS": 512
"NUM_STEPS": 168
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"LAYER_WIDTH": 512
"SEED": 50
"ANNEAL_LR": True

# WandB Params
"WANDB_MODE": "online"
"ENTITY": "yang12788"
"PROJECT": "jaxmarl-yokai"