"LR": 5e-4
"NUM_ENVS": 2
"NUM_STEPS": 112
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENV_NAME": "yokai_game"
"ENV_KWARGS": {}
"ANNEAL_LR": True
"SEED": 50
# WandB Params
"ENTITY": ""
"PROJECT": "jaxmarl-yokai"
"WANDB_MODE": "disabled"